version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: ipdb
    versions:
    - 0.13.5
    - 0.13.6
  - dependency-name: flake8-bugbear
    versions:
    - 21.3.1
    - 21.3.2
  - dependency-name: torchvision
    versions:
    - 0.8.2
    - 0.9.0
  - dependency-name: pyroma
    versions:
    - 2.6.1
    - 3.0.1
  - dependency-name: ipython
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: mypy
    versions:
    - "0.800"
